version: '3.7'
services:
  access-products:
    image: access-products
    environment:
      PORT: 8080
      DB_HOST: 'mongo'
      DB_USER: 'brandDiscountsUser'
      DB_PASSWORD: ${DB_SECRET_PASSWORD}
    ports:
      - "8080:8080"
    extra_hosts:
      - "mongo:${MACHINE_IP}"
