version: '3.7'
services:
  access-products:
    image: access-products
    environment:
      PORT: 8080
      DB_HOST: 'mongo'
    ports:
      - "8080:8080"
    extra_hosts: 
      - "mongo:${IP_DB}"
