version: '3.7'
services:
  ms-products:
    image: ms-products
    environment:
      PORT: 8081
      DB_HOST: 'mongo'
      DB_USER: 'brandDiscountsUser'
      DB_PASSWORD: ${DB_SECRET_PASSWORD}
    ports:
      - "8081:8081"
    extra_hosts:
      - "mongo:${MACHINE_IP}"
